"""Built-in learning cards seeded into the database on first startup."""

CARDS = [{'id': 1,
  'words': [{'en': 'time', 'ru': 'время'},
            {'en': 'person', 'ru': 'человек'},
            {'en': 'year', 'ru': 'год'},
            {'en': 'way', 'ru': 'путь'},
            {'en': 'day', 'ru': 'день'},
            {'en': 'thing', 'ru': 'вещь'},
            {'en': 'man', 'ru': 'мужчина'},
            {'en': 'world', 'ru': 'мир'},
            {'en': 'life', 'ru': 'жизнь'},
            {'en': 'hand', 'ru': 'рука'}]},
 {'id': 2,
  'words': [{'en': 'part', 'ru': 'часть'},
            {'en': 'child', 'ru': 'ребёнок'},
            {'en': 'eye', 'ru': 'глаз'},
            {'en': 'woman', 'ru': 'женщина'},
            {'en': 'place', 'ru': 'место'},
            {'en': 'work', 'ru': 'работа'},
            {'en': 'week', 'ru': 'неделя'},
            {'en': 'case', 'ru': 'случай'},
            {'en': 'point', 'ru': 'точка'},
            {'en': 'government', 'ru': 'правительство'}]},
 {'id': 3,
  'words': [{'en': 'company', 'ru': 'компания'},
            {'en': 'number', 'ru': 'число'},
            {'en': 'group', 'ru': 'группа'},
            {'en': 'problem', 'ru': 'проблема'},
            {'en': 'fact', 'ru': 'факт'},
            {'en': 'house', 'ru': 'дом'},
            {'en': 'water', 'ru': 'вода'},
            {'en': 'room', 'ru': 'комната'},
            {'en': 'mother', 'ru': 'мать'},
            {'en': 'area', 'ru': 'район'}]},
 {'id': 4,
  'words': [{'en': 'money', 'ru': 'деньги'},
            {'en': 'story', 'ru': 'история'},
            {'en': 'month', 'ru': 'месяц'},
            {'en': 'lot', 'ru': 'много'},
            {'en': 'right', 'ru': 'право'},
            {'en': 'study', 'ru': 'учёба'},
            {'en': 'book', 'ru': 'книга'},
            {'en': 'job', 'ru': 'работа'},
            {'en': 'word', 'ru': 'слово'},
            {'en': 'business', 'ru': 'бизнес'}]},
 {'id': 5,
  'words': [{'en': 'issue', 'ru': 'вопрос'},
            {'en': 'side', 'ru': 'сторона'},
            {'en': 'kind', 'ru': 'вид'},
            {'en': 'head', 'ru': 'голова'},
            {'en': 'home', 'ru': 'дом'},
            {'en': 'friend', 'ru': 'друг'},
            {'en': 'family', 'ru': 'семья'},
            {'en': 'power', 'ru': 'сила'},
            {'en': 'school', 'ru': 'школа'},
            {'en': 'system', 'ru': 'система'}]},
 {'id': 6,
  'words': [{'en': 'program', 'ru': 'программа'},
            {'en': 'question', 'ru': 'вопрос'},
            {'en': 'effort', 'ru': 'усилие'},
            {'en': 'authority', 'ru': 'власть'},
            {'en': 'method', 'ru': 'метод'},
            {'en': 'city', 'ru': 'город'},
            {'en': 'team', 'ru': 'команда'},
            {'en': 'body', 'ru': 'тело'},
            {'en': 'health', 'ru': 'здоровье'},
            {'en': 'car', 'ru': 'машина'}]},
 {'id': 7,
  'words': [{'en': 'computer', 'ru': 'компьютер'},
            {'en': 'table', 'ru': 'стол'},
            {'en': 'door', 'ru': 'дверь'},
            {'en': 'street', 'ru': 'улица'},
            {'en': 'country', 'ru': 'страна'},
            {'en': 'market', 'ru': 'рынок'},
            {'en': 'price', 'ru': 'цена'},
            {'en': 'food', 'ru': 'еда'},
            {'en': 'weather', 'ru': 'погода'},
            {'en': 'news', 'ru': 'новости'}]},
 {'id': 8,
  'words': [{'en': 'phone', 'ru': 'телефон'},
            {'en': 'picture', 'ru': 'картина'},
            {'en': 'idea', 'ru': 'идея'},
            {'en': 'reason', 'ru': 'причина'},
            {'en': 'research', 'ru': 'исследование'},
            {'en': 'girl', 'ru': 'девочка'},
            {'en': 'boy', 'ru': 'мальчик'},
            {'en': 'moment', 'ru': 'момент'},
            {'en': 'air', 'ru': 'воздух'},
            {'en': 'teacher', 'ru': 'учитель'}]},
 {'id': 9,
  'words': [{'en': 'force', 'ru': 'сила'},
            {'en': 'education', 'ru': 'образование'},
            {'en': 'foot', 'ru': 'нога'},
            {'en': 'animal', 'ru': 'животное'},
            {'en': 'music', 'ru': 'музыка'},
            {'en': 'color', 'ru': 'цвет'},
            {'en': 'paper', 'ru': 'бумага'},
            {'en': 'land', 'ru': 'земля'},
            {'en': 'product', 'ru': 'продукт'},
            {'en': 'meal', 'ru': 'приём пищи'}]},
 {'id': 10,
  'words': [{'en': 'game', 'ru': 'игра'},
            {'en': 'movie', 'ru': 'фильм'},
            {'en': 'subject', 'ru': 'предмет'},
            {'en': 'light', 'ru': 'свет'},
            {'en': 'type', 'ru': 'тип'},
            {'en': 'office', 'ru': 'офис'},
            {'en': 'class', 'ru': 'класс'},
            {'en': 'center', 'ru': 'центр'},
            {'en': 'park', 'ru': 'парк'},
            {'en': 'church', 'ru': 'церковь'}]},
 {'id': 11,
  'words': [{'en': 'hospital', 'ru': 'больница'},
            {'en': 'tree', 'ru': 'дерево'},
            {'en': 'river', 'ru': 'река'},
            {'en': 'mountain', 'ru': 'гора'},
            {'en': 'ocean', 'ru': 'океан'},
            {'en': 'island', 'ru': 'остров'},
            {'en': 'sky', 'ru': 'небо'},
            {'en': 'sun', 'ru': 'солнце'},
            {'en': 'moon', 'ru': 'луна'},
            {'en': 'star', 'ru': 'звезда'}]},
 {'id': 12,
  'words': [{'en': 'earth', 'ru': 'земля'},
            {'en': 'wind', 'ru': 'ветер'},
            {'en': 'rain', 'ru': 'дождь'},
            {'en': 'snow', 'ru': 'снег'},
            {'en': 'ice', 'ru': 'лёд'},
            {'en': 'fire', 'ru': 'огонь'},
            {'en': 'stone', 'ru': 'камень'},
            {'en': 'wood', 'ru': 'древесина'},
            {'en': 'metal', 'ru': 'металл'},
            {'en': 'glass', 'ru': 'стекло'}]},
 {'id': 13,
  'words': [{'en': 'window', 'ru': 'окно'},
            {'en': 'wall', 'ru': 'стена'},
            {'en': 'floor', 'ru': 'пол'},
            {'en': 'roof', 'ru': 'крыша'},
            {'en': 'key', 'ru': 'ключ'},
            {'en': 'lock', 'ru': 'замок'},
            {'en': 'box', 'ru': 'коробка'},
            {'en': 'bag', 'ru': 'сумка'},
            {'en': 'shirt', 'ru': 'рубашка'},
            {'en': 'check', 'ru': 'проверка'}]},
 {'id': 14,
  'words': [{'en': 'shoes', 'ru': 'обувь'},
            {'en': 'hat', 'ru': 'шляпа'},
            {'en': 'coat', 'ru': 'пальто'},
            {'en': 'dress', 'ru': 'платье'},
            {'en': 'pants', 'ru': 'брюки'},
            {'en': 'socks', 'ru': 'носки'},
            {'en': 'gloves', 'ru': 'перчатки'},
            {'en': 'scarf', 'ru': 'шарф'},
            {'en': 'belt', 'ru': 'ремень'},
            {'en': 'watch', 'ru': 'часы'}]},
 {'id': 15,
  'words': [{'en': 'ring', 'ru': 'кольцо'},
            {'en': 'necklace', 'ru': 'ожерелье'},
            {'en': 'bracelet', 'ru': 'браслет'},
            {'en': 'coin', 'ru': 'монета'},
            {'en': 'bill', 'ru': 'купюра'},
            {'en': 'card', 'ru': 'карта'},
            {'en': 'ticket', 'ru': 'билет'},
            {'en': 'passport', 'ru': 'паспорт'},
            {'en': 'license', 'ru': 'лицензия'},
            {'en': 'degree', 'ru': 'степень'}]},
 {'id': 16,
  'words': [{'en': 'award', 'ru': 'награда'},
            {'en': 'prize', 'ru': 'приз'},
            {'en': 'trophy', 'ru': 'кубок'},
            {'en': 'medal', 'ru': 'медаль'},
            {'en': 'badge', 'ru': 'значок'},
            {'en': 'flag', 'ru': 'флаг'},
            {'en': 'sign', 'ru': 'знак'},
            {'en': 'symbol', 'ru': 'символ'},
            {'en': 'logo', 'ru': 'логотип'},
            {'en': 'brand', 'ru': 'бренд'}]},
 {'id': 17,
  'words': [{'en': 'shop', 'ru': 'магазин'},
            {'en': 'store', 'ru': 'лавка'},
            {'en': 'mall', 'ru': 'молл'},
            {'en': 'bank', 'ru': 'банк'},
            {'en': 'hotel', 'ru': 'отель'},
            {'en': 'cafe', 'ru': 'кафе'},
            {'en': 'restaurant', 'ru': 'ресторан'},
            {'en': 'bar', 'ru': 'бар'},
            {'en': 'club', 'ru': 'клуб'},
            {'en': 'cinema', 'ru': 'кинотеатр'}]},
 {'id': 18,
  'words': [{'en': 'theater', 'ru': 'театр'},
            {'en': 'museum', 'ru': 'музей'},
            {'en': 'library', 'ru': 'библиотека'},
            {'en': 'university', 'ru': 'университет'},
            {'en': 'college', 'ru': 'колледж'},
            {'en': 'academy', 'ru': 'академия'},
            {'en': 'institute', 'ru': 'институт'},
            {'en': 'laboratory', 'ru': 'лаборатория'},
            {'en': 'factory', 'ru': 'фабрика'},
            {'en': 'warehouse', 'ru': 'склад'}]},
 {'id': 19,
  'words': [{'en': 'station', 'ru': 'станция'},
            {'en': 'airport', 'ru': 'аэропорт'},
            {'en': 'harbor', 'ru': 'гавань'},
            {'en': 'bridge', 'ru': 'мост'},
            {'en': 'tunnel', 'ru': 'тоннель'},
            {'en': 'road', 'ru': 'дорога'},
            {'en': 'highway', 'ru': 'шоссе'},
            {'en': 'path', 'ru': 'тропа'},
            {'en': 'trail', 'ru': 'маршрут'},
            {'en': 'route', 'ru': 'путь'}]},
 {'id': 20,
  'words': [{'en': 'vehicle', 'ru': 'транспорт'},
            {'en': 'bus', 'ru': 'автобус'},
            {'en': 'train', 'ru': 'поезд'},
            {'en': 'plane', 'ru': 'самолёт'},
            {'en': 'ship', 'ru': 'корабль'},
            {'en': 'boat', 'ru': 'лодка'},
            {'en': 'bicycle', 'ru': 'велосипед'},
            {'en': 'truck', 'ru': 'грузовик'},
            {'en': 'taxi', 'ru': 'такси'},
            {'en': 'ambulance', 'ru': 'скорая'}]},
 {'id': 21,
  'words': [{'en': 'police', 'ru': 'полиция'},
            {'en': 'doctor', 'ru': 'врач'},
            {'en': 'nurse', 'ru': 'медсестра'},
            {'en': 'lawyer', 'ru': 'юрист'},
            {'en': 'judge', 'ru': 'судья'},
            {'en': 'engineer', 'ru': 'инженер'},
            {'en': 'architect', 'ru': 'архитектор'},
            {'en': 'artist', 'ru': 'художник'},
            {'en': 'writer', 'ru': 'писатель'},
            {'en': 'pilot', 'ru': 'пилот'}]},
 {'id': 22,
  'words': [{'en': 'singer', 'ru': 'певец'},
            {'en': 'dancer', 'ru': 'танцор'},
            {'en': 'actor', 'ru': 'актёр'},
            {'en': 'director', 'ru': 'режиссёр'},
            {'en': 'producer', 'ru': 'продюсер'},
            {'en': 'coach', 'ru': 'тренер'},
            {'en': 'player', 'ru': 'игрок'},
            {'en': 'fan', 'ru': 'фанат'},
            {'en': 'crowd', 'ru': 'толпа'},
            {'en': 'audience', 'ru': 'аудитория'}]},
 {'id': 23,
  'words': [{'en': 'leader', 'ru': 'лидер'},
            {'en': 'manager', 'ru': 'менеджер'},
            {'en': 'worker', 'ru': 'рабочий'},
            {'en': 'boss', 'ru': 'начальник'},
            {'en': 'employee', 'ru': 'сотрудник'},
            {'en': 'customer', 'ru': 'клиент'},
            {'en': 'guest', 'ru': 'гость'},
            {'en': 'host', 'ru': 'хозяин'},
            {'en': 'neighbor', 'ru': 'сосед'},
            {'en': 'colleague', 'ru': 'коллега'}]},
 {'id': 24,
  'words': [{'en': 'brother', 'ru': 'брат'},
            {'en': 'sister', 'ru': 'сестра'},
            {'en': 'uncle', 'ru': 'дядя'},
            {'en': 'aunt', 'ru': 'тётя'},
            {'en': 'cousin', 'ru': 'двоюродный брат'},
            {'en': 'nephew', 'ru': 'племянник'},
            {'en': 'niece', 'ru': 'племянница'},
            {'en': 'husband', 'ru': 'муж'},
            {'en': 'wife', 'ru': 'жена'},
            {'en': 'spouse', 'ru': 'супруг'}]},
 {'id': 25,
  'words': [{'en': 'parent', 'ru': 'родитель'},
            {'en': 'grandparent', 'ru': 'бабушка/дедушка'},
            {'en': 'ancestor', 'ru': 'предок'},
            {'en': 'descendant', 'ru': 'потомок'},
            {'en': 'relative', 'ru': 'родственник'},
            {'en': 'enemy', 'ru': 'враг'},
            {'en': 'rival', 'ru': 'соперник'},
            {'en': 'partner', 'ru': 'партнёр'},
            {'en': 'ally', 'ru': 'союзник'},
            {'en': 'stranger', 'ru': 'незнакомец'}]},
 {'id': 26,
  'words': [{'en': 'peace', 'ru': 'мир'},
            {'en': 'war', 'ru': 'война'},
            {'en': 'battle', 'ru': 'битва'},
            {'en': 'fight', 'ru': 'бой'},
            {'en': 'conflict', 'ru': 'конфликт'},
            {'en': 'agreement', 'ru': 'соглашение'},
            {'en': 'treaty', 'ru': 'договор'},
            {'en': 'contract', 'ru': 'контракт'},
            {'en': 'deal', 'ru': 'сделка'},
            {'en': 'offer', 'ru': 'предложение'}]},
 {'id': 27,
  'words': [{'en': 'request', 'ru': 'запрос'},
            {'en': 'demand', 'ru': 'требование'},
            {'en': 'order', 'ru': 'приказ'},
            {'en': 'rule', 'ru': 'правило'},
            {'en': 'law', 'ru': 'закон'},
            {'en': 'regulation', 'ru': 'регулирование'},
            {'en': 'policy', 'ru': 'политика'},
            {'en': 'strategy', 'ru': 'стратегия'},
            {'en': 'plan', 'ru': 'план'},
            {'en': 'goal', 'ru': 'цель'}]},
 {'id': 28,
  'words': [{'en': 'dream', 'ru': 'мечта'},
            {'en': 'hope', 'ru': 'надежда'},
            {'en': 'wish', 'ru': 'желание'},
            {'en': 'fear', 'ru': 'страх'},
            {'en': 'joy', 'ru': 'радость'},
            {'en': 'sadness', 'ru': 'грусть'},
            {'en': 'anger', 'ru': 'злость'},
            {'en': 'love', 'ru': 'любовь'},
            {'en': 'hate', 'ru': 'ненависть'},
            {'en': 'respect', 'ru': 'уважение'}]},
 {'id': 29,
  'words': [{'en': 'trust', 'ru': 'доверие'},
            {'en': 'faith', 'ru': 'вера'},
            {'en': 'doubt', 'ru': 'сомнение'},
            {'en': 'truth', 'ru': 'правда'},
            {'en': 'lie', 'ru': 'ложь'},
            {'en': 'secret', 'ru': 'секрет'},
            {'en': 'mystery', 'ru': 'загадка'},
            {'en': 'puzzle', 'ru': 'головоломка'},
            {'en': 'riddle', 'ru': 'загадка'},
            {'en': 'joke', 'ru': 'шутка'}]},
 {'id': 30,
  'words': [{'en': 'laughter', 'ru': 'смех'},
            {'en': 'smile', 'ru': 'улыбка'},
            {'en': 'tear', 'ru': 'слеза'},
            {'en': 'sigh', 'ru': 'вздох'},
            {'en': 'shout', 'ru': 'крик'},
            {'en': 'whisper', 'ru': 'шёпот'},
            {'en': 'voice', 'ru': 'голос'},
            {'en': 'sound', 'ru': 'звук'},
            {'en': 'silence', 'ru': 'молчание'},
            {'en': 'noise', 'ru': 'шум'}]},
 {'id': 99, 'words': []}]
